#!/usr/bin/python3
"""spec-xanmod.py - turn a pristine Fedora kernel.spec into the XanMod spec.

Everything this script does is intentionally tiny and load-bearing:

  * an override block prepended to the file. Fedora's build knobs are all
    ``%{?_with_foo}`` / ``%{?_without_foo}`` lookups, so defining them up front
    is enough - no need to edit the lines that consume them.
  * the package name, so the copr package is kernel-xanmod and not kernel.
  * the version defines, from the XanMod tag.

Deliberately *not* touched:

  * ``Source0``/``%setup``: tools/get-source.sh produces exactly the
    linux-<version>.tar.xz layout Fedora already expects.
  * ``kabiversion``: it names the two kABI tarballs that come from Fedora's
    lookaside cache, so it has to keep tracking Fedora, not XanMod.
  * ``pkgrelease``/``specrelease``: Fedora's release number is what gives us an
    upgrade path when Fedora rebases the same kernel version.
  * every ``Source``/``Patch`` line: fedora/ is a full dist-git mirror, so all of
    those files exist.

Each edit must match exactly once. A Fedora refactor that breaks an assumption
fails the build here instead of producing a subtly wrong kernel.
"""

import argparse
import re
import sys

OVERRIDES = """\
# --- XanMod overrides: generated by tools/spec-xanmod.py, do not edit ---
# Fedora's downstream patch does not apply to the XanMod tree. with_vanilla
# gives us nopatches=1 (skips patch-%{{patchversion}}-redhat.patch) and, as a
# side effect, with_configchecks=0, which we need because the XanMod tree has
# config symbols Fedora's configs never mention.
%define _with_vanilla 1
# No separate debug kernel and no debuginfo packages: they roughly double copr
# build time and nobody debugs this kernel with them.
%define _without_debug 1
%define _without_debuginfo 1
# kernel-xanmod-rt. Fedora defaults realtime off and only builds it on request;
# the rt configs themselves ship in dist-git either way.
%define _with_realtime 1
# Release tag, ends up in the rpm release as e.g. 61.xanmod1.fc45
%define buildid .{buildid}
# --- end XanMod overrides ---
"""


def sub_once(text, pattern, repl, what):
    new, n = re.subn(pattern, repl, text, flags=re.M)
    if n != 1:
        sys.exit(
            f"ERROR: {what}: expected exactly 1 match for /{pattern}/, got {n}. "
            "Fedora's spec changed shape - tools/spec-xanmod.py needs updating."
        )
    print(f"  {what}")
    return new


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec")
    ap.add_argument("--version", required=True, help="XanMod kernel version, e.g. 7.2.0")
    ap.add_argument("--package-name", default="kernel-xanmod")
    ap.add_argument("--buildid", default="xanmod1")
    args = ap.parse_args()

    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", args.version)
    if not m:
        sys.exit(f"ERROR: --version {args.version!r} is not X.Y.Z")
    kversion, patchlevel, _sublevel = m.groups()
    series = f"{kversion}.{patchlevel}"

    with open(args.spec) as f:
        spec = f.read()

    print(f"Rewriting {args.spec} for XanMod {args.version}:")
    spec = OVERRIDES.format(buildid=args.buildid) + spec
    print("  prepended override block")

    spec = sub_once(
        spec,
        r"^%global package_name kernel$",
        f"%global package_name {args.package_name}",
        f"package_name -> {args.package_name}",
    )

    for define, value in (
        ("specrpmversion", args.version),
        ("specversion", args.version),
        ("tarfile_release", args.version),
        ("patchversion", series),
        ("kversion", kversion),
        ("patchlevel", patchlevel),
    ):
        spec = sub_once(
            spec,
            rf"^%define {define} .*$",
            f"%define {define} {value}",
            f"{define} -> {value}",
        )

    # Guard the assumptions the rest of the pipeline relies on.
    for needed, why in (
        (rf"^Source0: linux-%\{{tarfile_release\}}\.tar\.xz$", "Source0 tarball name"),
        (r"^%setup -q -n kernel-%\{tarfile_release\} -c$", "%setup layout"),
        (r"^mv linux-%\{tarfile_release\} linux-%\{KVERREL\}$", "source dir rename"),
        (r"^Source3001: kernel-local$", "kernel-local config hook"),
        (r"^Source2: %\{name\}\.changelog$", "changelog naming"),
        # tools/assemble.sh keeps the arch marker on line 1 of the config it
        # generates because of this line. An empty ARCH= reaches make as
        # defined-but-empty and the build dies on arch//Makefile.
        (r"^\s*Arch=`head -1 \.config \| cut -b 3-`$", "ARCH read from config line 1"),
    ):
        if not re.search(needed, spec, flags=re.M):
            sys.exit(
                f"ERROR: {why}: expected /{needed}/ in the pristine spec but it is gone. "
                "Fedora changed something tools/assemble.sh depends on."
            )

    with open(args.spec, "w") as f:
        f.write(spec)


if __name__ == "__main__":
    main()
